language: node_js
node_js:
- 0.1
env:
  global:
    - secure: iirlsI44KY6iIDmUW3VMVsAMrv7uae662hUYfrZQSuyybfVFaqXZkvrEiRpTTfNQ05dCBr4V6qGrhCXJse54hZ3yP/00WrJpb8E1A0orImWKgBGqQyZbbvnhdLi6Y8vc5RzAEnWucp0e9/oNeNR7yictcKVkmGCTpW9jnX9yMRU=
    - secure: XocB0P7LBy5MvJjS4e1ex3ZmA6FItD80V+nCTsUPdeVTS9xM2O50cL4037hPPzY1ZNfHpD4ciJ9IKkC2AlqYD2Bewh6PijPOClMcW1Gun7pM1hUSe42WtLKga9JGJ/SZTqMcDht8Z+ZEcWWUc9Nf29j0Z9dnzeFNVtJ570DfRX8=
