ui: tape
browsers:
  - name: safari
    version: latest
  - name: chrome
    version: 27..latest
  - name: firefox
    version: 33..latest
  - name: ie
    version: latest
  - name: iphone
    version: latest
